/* Mountain Objective Planner — single complete PDF exporter */
async function mopImageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1400,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve({data:c.toDataURL('image/jpeg',.76),w:c.width,h:c.height,name:file.name})};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function mopPdf(finalMode){note('Building complete PDF…');if(!window.jspdf){alert('PDF engine did not load. Please refresh the planner while online and try again.');return}try{const o=data(),{jsPDF}=window.jspdf,d=new jsPDF({unit:'pt',format:'letter',compress:true}),W=612,H=792,M=44,R=568,TOP=46,BOT=58,C='#17374d',TEXT='#1f2933',MUTED='#60717a',PLANNER='https://mountain-objective-planning-tool-ct.vercel.app/';let y=TOP;
const newPage=()=>{d.addPage();y=TOP};const avail=()=>H-BOT-y;const ensure=n=>{if(avail()<n)newPage()};
const writeLines=(value,size=10,style='normal',indent=0)=>{const text=String(value==null||value===''?'—':value),width=R-M-indent;d.setFont('helvetica',style);d.setFontSize(size);d.setTextColor(TEXT);const paras=text.split(/\n/);for(let pi=0;pi<paras.length;pi++){const lines=d.splitTextToSize(paras[pi]||' ',width);for(const line of lines){const lh=size*1.35;ensure(lh+3);d.text(line,M+indent,y);y+=lh}if(pi<paras.length-1)y+=size*.35}};
const heading=h=>{ensure(42);d.setFillColor(C);d.roundedRect(M,y,R-M,23,4,4,'F');d.setTextColor('#fff');d.setFont('helvetica','bold');d.setFontSize(10);d.text(String(h).toUpperCase(),M+9,y+15);y+=34};
const section=(h,b)=>{heading(h);writeLines(b,10);y+=12};
const cover=()=>{d.setFillColor(C);d.rect(0,0,W,110,'F');d.setTextColor('#fff');d.setFont('helvetica','bold');d.setFontSize(21);d.text(finalMode?'MOUNTAIN OBJECTIVE — FINAL RECORD':'MOUNTAIN OBJECTIVE — PLAN',M,45);d.setFontSize(15);const title=d.splitTextToSize(o.name||'Untitled Objective',520);d.text(title,M,72);d.setFont('helvetica','normal');d.setFontSize(9);d.text(`${o.sd||'—'} to ${o.ed||'—'}  |  ${o.loc||'—'}  |  ${o.env||'—'}`,M,99);y=136};cover();
section('Objective & Team',`Team Lead: ${o.lead||'—'}\nTeam Members: ${o.team||'—'}`);section('Most Dangerous Part of Objective',`${o.haz||'—'}\n${o.danger||'—'}`);section('Weather',`${o.trend||'—'} | ${o.light||'—'}\n${o.weather||'—'}`);section('Route & Decision Plan',o.route);section('Abort Criteria / Turnaround',o.abort);section('Contingency / Retreat',o.cont);section('Packing List / Equipment',o.gear);section('Medical / Rescue',o.med);section('Communications / PACE',o.comms);
if(finalMode){heading('Execution / Field Log');if(!logs.length){writeLines('No execution entries recorded.')}else{for(let i=0;i<logs.length;i++){const l=logs[i];ensure(42);d.setFont('helvetica','bold');d.setFontSize(10);d.setTextColor(C);d.text(`${l.time||'—'} | ${l.type||'Entry'} | ${l.loc||'—'}`,M,y);y+=15;writeLines(l.note||'—',10);if(l.photoData&&l.photoW&&l.photoH){let maxW=R-M,maxH=350,r=Math.min(maxW/l.photoW,maxH/l.photoH),iw=l.photoW*r,ih=l.photoH*r;if(ih>avail()-18){newPage();r=Math.min(maxW/l.photoW,(H-TOP-BOT-30)/l.photoH);iw=l.photoW*r;ih=l.photoH*r}d.addImage(l.photoData,'JPEG',M,y,iw,ih,undefined,'FAST');y+=ih+12}y+=10}}y+=6;section('AAR — Sustain',o.sustain);section('AAR — Improve',o.improve);section('Lessons / Recommendations',o.lessons)}
const pages=d.getNumberOfPages();for(let i=1;i<=pages;i++){d.setPage(i);d.setDrawColor('#d4dde1');d.line(M,H-45,R,H-45);d.setFont('helvetica','normal');d.setFontSize(8);d.setTextColor(MUTED);d.text('Mountain Objective Planner',M,H-30);d.text(`Page ${i} of ${pages}`,R,H-30,{align:'right'});d.setTextColor('#174f72');d.setFont('helvetica','bold');d.textWithLink('OPEN A FRESH MOUNTAIN OBJECTIVE PLAN',M,H-17,{url:PLANNER})}
const blob=d.output('blob'),fn=safe()+(finalMode?'_FINAL_Plan_Execution_AAR.pdf':'_Plan.pdf'),file=new File([blob],fn,{type:'application/pdf'});note('PDF complete — opening save/share options…');if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({title:o.name||'Mountain Objective',files:[file]});note('Single PDF created successfully.');return}catch(e){if(e.name==='AbortError'){note('PDF save cancelled.');return}}}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=fn;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);note('Single PDF downloaded.')}catch(e){console.error(e);alert('The PDF could not be created. Please refresh the planner and try again.')}}