(()=>{
 const $=id=>document.getElementById(id),v=id=>$(id)?.value||'',notify=id=>$(id)?.dispatchEvent(new Event('change',{bubbles:true}));
 let searchSerial=0,importSerial=0,controller,timer,lastQuery='',page=1,photoSerial=0,applying=false;
 const fields=['routeSource','routeGrade','routeType','routeLength','routeProtection','routeApproach','routeDescription','routePitches','routeAreaInfo','routeComments','routeSoWhat','routePhotoReferences'];
 const status=(text)=>{$('routeSearchStatus').textContent=text;};
 function set(id,text){if($(id)){$(id).value=String(text??'');notify(id);}}
 function selectValue(id,value){const e=$(id);if(!e)return;if(e.tagName==='SELECT'&&value&&![...e.options].some(o=>o.value===value)){const o=new Option(value,value);e.add(o);}e.value=value;notify(id);}
 function showSource(){let data;try{data=JSON.parse(v('routeImportedData')||'null');}catch(_){};$('routeImportSummary').textContent=data?'Imported '+data.name+' • OpenBeta / CC0 • '+data.retrieved+(v('name')!==data.name?' • Route name changed: confirm that the imported information still applies.':''):'Search above to import openly licensed route facts, or enter the climbing brief manually.';}
 async function search(next=1){const query=v('name').trim();if(query.length<2){status('Enter at least two characters of a route, mountain or climbing area.');return;}controller?.abort();controller=new AbortController();const serial=++searchSerial;status('Searching open route catalog…');$('routeSearchButton').disabled=true;
  try{const r=await fetch('/api/route-search?'+new URLSearchParams({q:query,page:next}),{signal:controller.signal}),d=await r.json();if(!r.ok)throw Error(d.error||'Search unavailable.');if(serial!==searchSerial)return;lastQuery=query;page=next;$('routeSearchResults').replaceChildren();for(const item of d.results){const button=document.createElement('button');button.type='button';button.className='route-result';const title=document.createElement('strong'),location=document.createElement('span');title.textContent=item.name;location.textContent=item.location;button.append(title,location);button.onclick=()=>importRoute(item.id);$('routeSearchResults').appendChild(button);}$('routeSearchPrevious').hidden=next===1;$('routeSearchNext').hidden=!d.hasMore;status((d.total?d.total.toLocaleString()+' matches • page '+next:'No matches. Use manual entry or refine the route / area name.')+' • '+d.catalogCount.toLocaleString()+' catalog routes • snapshot '+d.catalogDate.slice(0,10));}
  catch(e){if(e.name!=='AbortError'&&serial===searchSerial)status(e.message+' Manual route entry is available.');}finally{if(serial===searchSerial)$('routeSearchButton').disabled=false;}
 }


 async function sourceJSON(url,attempts=2){for(let i=0;i<attempts;i++){try{const r=await fetch(url,{signal:AbortSignal.timeout(65000)}),d=await r.json();if(r.ok)return d;const error=Error(d.error||'Source data unavailable');error.retryable=r.status>=500||r.status===429;error.retryAfter=Number(r.headers.get('Retry-After'));throw error;}catch(e){if(e.retryable===false||i===attempts-1)throw e;await new Promise(resolve=>setTimeout(resolve,Number.isFinite(e.retryAfter)&&e.retryAfter>0?Math.min(e.retryAfter*1000,5000):750*(i+1)));}}}
 function confirmNeeded(){return fields.some(id=>v(id).trim())||/^(https?:\/\/)/.test(v('maplink'));}
 async function importRoute(id){const serial=++importSerial;status('Retrieving route facts, all available native climber notes and photo references…');$('routeSearchButton').disabled=true;
  try{const d=await sourceJSON('/api/route-details?'+new URLSearchParams({id}));if(serial!==importSerial)return;
   if(confirmNeeded()&&!confirm('Replace the imported climbing brief and primary route link with '+d.name+'? Your team decision notes and equipment notes remain; risk categories will require reassessment.'))return;
   // Apply a selected route only after the complete response, preserving the prior plan on errors.
   ++photoSerial;set('routePhotoManifest','[]');set('routeImportedData',JSON.stringify(d));set('routeImportedId',d.id);set('name',d.name);set('locationCitySearch','');
   const country=d.path[0]==='USA'?'United States':d.path[0]||'';selectValue('country',country);
   const stateName=d.path[1]||'';const match=[...$('state').options].find(o=>o.textContent.replace(/ \([A-Z]{2}\)$/,'').toLowerCase()===stateName.toLowerCase());selectValue('state',match?.value||stateName);selectValue('city','');
   set('loc',d.path.slice(2).join(' / ')||d.path.join(' / '));set('maplink',d.url);
   const env=d.types.includes('mixed')?'Mixed Climb / Other':d.types.includes('ice')?'Ice Climb':d.types.includes('snow')?'Snow / Glacier':'Rock / Alpine';$('env').value=env;
   // Prior route ratings cannot establish risk for the newly selected objective.
   for(const e of document.querySelectorAll('#plan select[id]'))if(/^(tl_|rd_|wx_|rt_|hz_|med_|cm_|av_|res_|rock_|ice_|ski_|sm_|mx_|ss_)/.test(e.id))e.value='';
   set('autoWeatherReview','');set('autoAvReview','');set('latitude',d.coordinates?.[0]??'');set('longitude',d.coordinates?.[1]??'');if(d.coordinates)set('forecastMode','Automatic Data');applying=true;notify('env');applying=false;document.dispatchEvent(new Event('mop-route-pin'));
   set('routeSource',d.name+'\n'+d.url+'\nOpenBeta route text: CC0-1.0\nRetrieved: '+d.retrieved+'\n'+d.coordinateBasis);
   set('routeGrade',d.grade||'Incomplete — grade not provided by source');
   const sourceYds=(d.grade.match(/\bYDS:\s*([^·]+)/i)||[])[1]?.trim(),sourceWi=(d.grade.match(/\bWI:\s*([^·]+)/i)||[])[1]?.trim();for(const [id,grade] of [['rock_yds',sourceYds],['ice_wi',sourceWi?/^WI/i.test(sourceWi)?sourceWi:'WI'+sourceWi:'']]){const e=$(id);if(e&&grade&&[...e.options].some(o=>o.value===grade))selectValue(id,grade);}
set('routeType',d.types.join(', ')||'Incomplete — type not provided');set('routeLength',(d.lengthFt==null?'Length: Incomplete':d.lengthFt+' ft climbing length')+' • '+(d.pitches.length?d.pitches.length+' structured pitches':'Pitch count: Incomplete')+(d.boltsCount==null?'':' • Published bolt / permanent anchor count: '+d.boltsCount)+'\nProtection rating: '+(d.safety==='UNSPECIFIED'?'Unspecified':d.safety||'Unspecified'));
   set('routeProtection',d.protection||'Incomplete — source does not provide protection information');set('routeApproach',d.approach||'Incomplete — source does not provide approach information');set('routeDescription',d.description||'Incomplete — source does not provide climb description');
   set('routePitches',d.pitches.map(p=>'P'+p.pitchNumber+' • '+(p.grade||'grade unavailable')+' • '+(p.lengthFt==null?'length unavailable':p.lengthFt+' ft')+'\n'+p.description).join('\n\n')||'Incomplete — structured pitch details not provided; do not infer pitch count');set('routeAreaInfo',d.areaDescription||'Area description not provided');
   set('routeComments',d.comments.map((c,i)=>'NOTE '+(i+1)+' • climbed '+(c.date||'date unknown')+'\n'+c.text+'\n'+d.url).join('\n\n')||(d.commentsUnavailable?'Incomplete — climber notes could not be retrieved':'No native OpenBeta climber notes returned. Mountain Project comments are not imported.'));
   set('routeSoWhat',d.soWhat);set('routePhotoReferences',d.photoReferences.map(p=>(p.username||'Unknown photographer')+' • '+p.width+' × '+p.height+' pixels\n'+p.mediaUrl+'\n'+p.license+'\nRoute source: '+d.url).join('\n\n')||d.photoReferenceError||'No OpenBeta route photo references returned.');
   showSource();$('routeSearchResults').replaceChildren();$('routeSearchNext').hidden=$('routeSearchPrevious').hidden=true;status('Imported '+d.name+'. Check the objective pin, complete the risk matrix and review the source-based So What.');if(typeof save==='function')save();
   $('routeClimbingBrief').scrollIntoView({behavior:'smooth',block:'start'});await importPhotos(d,serial);
  }catch(e){if(serial===importSerial)status(e.message);}finally{if(serial===importSerial)$('routeSearchButton').disabled=false;}
 }
 const safePhoto=p=>/^https:\/\/upload\.wikimedia\.org\//.test(p?.url||'')&&/^https:\/\/commons\.wikimedia\.org\//.test(p?.source||'')&&(/^https:\/\/creativecommons\.org\/(licenses\/by(?:-sa)?\/|publicdomain\/(?:zero|mark)\/)/.test(p?.licenseUrl||'')||/^(CC0|Public domain|PD)$/i.test(p?.license||''));
 let dbPromise;
 function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('mop-route-photos',1);req.onupgradeneeded=()=>req.result.createObjectStore('originals');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return dbPromise;}
 async function stored(key,blob){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('originals',blob?'readwrite':'readonly'),store=tx.objectStore('originals'),req=blob?store.put(blob,key):store.get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
 async function photoBlob(p){if(!safePhoto(p))throw Error('Photo reuse permission / source not verified.');const key=p.id+'|'+p.url;let b;try{b=await stored(key);}catch(_){};if(b)return b;const response=await fetch(p.url,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('Original photo unavailable');b=await response.blob();if(!b.type.startsWith('image/'))throw Error('Original is not an image');try{await stored(key,b);}catch(_){$('routePhotosStatus').textContent='Photo storage unavailable. Originals can be included in the PDF while connected; save the PDF before leaving coverage.';}return b;}
 window.mopRoutePhotoBlob=photoBlob;
 window.mopRoutePhotoList=()=>{try{return JSON.parse(v('routePhotoManifest')||'[]').filter(safePhoto);}catch(_){return[];}};
 const urls=[];
 async function renderPhotos(){for(const u of urls)URL.revokeObjectURL(u);urls.length=0;$('routePhotoGallery').replaceChildren();const token=photoSerial;for(const p of window.mopRoutePhotoList()){if(token!==photoSerial)return;const card=document.createElement('div');card.className='route-photo';const text=document.createElement('p');text.textContent=p.title+' • '+p.author+' • '+p.license+' • original '+p.width+' × '+p.height;const a=document.createElement('a');a.href=p.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='PHOTO SOURCE / LICENSE';card.append(text,a);$('routePhotoGallery').appendChild(card);try{const b=await photoBlob(p);if(token!==photoSerial)return;const u=URL.createObjectURL(b);urls.push(u);const im=new Image();im.alt=p.title;im.src=u;im.style.cssText='width:100%;height:auto;display:block;margin-top:8px';card.prepend(im);}catch(_){const msg=document.createElement('p');msg.textContent='Original download unavailable. Retry while connected; the PDF retains the photo source link.';card.appendChild(msg);}}}
 async function importPhotos(route,serial){const token=++photoSerial;let offset=0,photos=[],references=route.photoReferences||[],downloaded=0,failed=0;const seen=new Set();$('routePhotosStatus').textContent='Searching for openly licensed photos matching the route and area…';try{do{const d=await sourceJSON('/api/route-photos?'+new URLSearchParams({name:route.name,area:route.path.join(' / '),offset}),3);if(token!==photoSerial||serial!==importSerial)return;for(const p of d.photos||[]){if(!safePhoto(p)||seen.has(p.id))continue;seen.add(p.id);photos.push(p);try{await photoBlob(p);downloaded++;}catch(_){failed++;}$('routePhotosStatus').textContent=downloaded+' permitted originals downloaded; '+failed+' unavailable.';}if(d.references?.length)references.push(...d.references);set('routePhotoManifest',JSON.stringify(photos));const next=d.nextOffset;if(next==null)break;if(next<=offset)throw Error('Photo search pagination incomplete');offset=next;}while(true);
   $('routePhotosStatus').textContent=photos.length?downloaded+' of '+photos.length+' matching, permitted originals downloaded'+(failed?' • '+failed+' unavailable; source links retained':'')+'. Review image identity before briefing.':'No matching photos with confirmed reuse permission found. OpenBeta photo links are retained; you can attach permitted originals below.';
  }catch(e){if(token!==photoSerial)return;$('routePhotosStatus').textContent=e.message+' '+downloaded+' originals downloaded before the interruption.';}if(token!==photoSerial)return;set('routePhotoManifest',JSON.stringify(photos));set('routePhotoReferences',references.map(p=>[p.title||p.username||'Route photo',p.source||(/^https?:\/\//.test(p.mediaUrl||'')?p.mediaUrl:route.url),p.width&&p.height?'Original: '+p.width+' × '+p.height+' pixels':'',p.license||'Reuse permission not provided; link only.'].filter(Boolean).join('\n')).join('\n\n')||v('routePhotoReferences'));await renderPhotos();}
 function setup(){showSource();if(v('routeImportedId'))$('routePhotosStatus').textContent=window.mopRoutePhotoList().length+' permitted photo references restored; originals load below. Use Retry to check for additional photos.';$('routeSearchButton').onclick=()=>search();$('routeSearchNext').onclick=()=>{if(v('name')===lastQuery)search(page+1);};$('routeSearchPrevious').onclick=()=>{if(v('name')===lastQuery)search(page-1);};$('name').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search();}});$('name').addEventListener('input',()=>{++searchSerial;controller?.abort();$('routeSearchResults').replaceChildren();$('routeSearchNext').hidden=$('routeSearchPrevious').hidden=true;$('routeSearchButton').disabled=false;showSource();clearTimeout(timer);if(v('name').trim().length>=3)timer=setTimeout(()=>search(),700);});$('routePhotosRetry').onclick=()=>{let d;try{d=JSON.parse(v('routeImportedData'));}catch(_){};if(d)importPhotos(d,importSerial);else $('routePhotosStatus').textContent='Import a route first.';};document.addEventListener('change',e=>{if(e.target.id==='env'&&!applying){if(!v('routeImportedId')){++importSerial;++photoSerial;$('routeSearchButton').disabled=false;$('routePhotosStatus').textContent='Import a route to retrieve permitted photos.';}setTimeout(()=>{showSource();renderPhotos();},50);}});renderPhotos();}
 window.addEventListener('DOMContentLoaded',()=>setTimeout(setup,0));
})();
