const {plain,standard,brief}=require('./route-brief.cjs');
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function gql(query,variables){const u='https://api.openbeta.io/?'+new URLSearchParams({query,variables:JSON.stringify(variables||{})});const r=await fetch(u,{headers:{'Accept':'application/json','Content-Type':'application/json','User-Agent':'MountainObjectivePlanner/1.0 (OpenBeta route planning)'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('OpenBeta returned '+r.status);const d=await r.json();if(d.errors?.length)throw Error(d.errors[0].message);return d.data;}
const basic=`query Route($id:ID){climb(uuid:$id){uuid name length boltsCount grades{yds wi vscale french uiaa} safety type{trad sport alpine ice mixed snow aid bouldering tr} metadata{lat lng mp_id} pathTokens content{description location protection} pitches{pitchNumber length grades{yds wi}description} parent{uuid area_name content{description areaLocation}metadata{lat lng}}}}`;
async function getRoute(id){const data=await gql(basic,{id}),c=data.climb;if(!c)throw Error('Route no longer available in OpenBeta.');const grades=Object.entries(c.grades||{}).filter(([,v])=>v).map(([k,v])=>k.toUpperCase()+': '+v);const grade=grades.join(' · ');const coords=Number.isFinite(c.metadata?.lat)&&Number.isFinite(c.metadata?.lng)?[c.metadata.lat,c.metadata.lng]:Number.isFinite(c.parent?.metadata?.lat)&&Number.isFinite(c.parent?.metadata?.lng)?[c.parent.metadata.lat,c.parent.metadata.lng]:null;
 const r={id:c.uuid,name:plain(c.name),url:'https://openbeta.io/climb/'+c.uuid,license:'CC0-1.0',retrieved:new Date().toISOString(),path:c.pathTokens||[],grade,safety:c.safety||'',types:Object.entries(c.type||{}).filter(([,v])=>v).map(([k])=>k),lengthFt:c.length>0?Math.round(c.length*3.28084):null,boltsCount:c.boltsCount>=0?c.boltsCount:null,coordinates:coords,coordinateBasis:'Published route / crag coordinate; verify the exact objective pin on the map.',description:standard(c.content?.description),protection:standard(c.content?.protection),approach:[standard(c.content?.location),c.parent?.content?.areaLocation?'AREA APPROACH / LOCATION ('+plain(c.parent.area_name)+'): '+standard(c.parent.content.areaLocation):''].filter(Boolean).join('\n\n'),areaDescription:standard(c.parent?.content?.description),pitches:(c.pitches||[]).map(p=>({pitchNumber:p.pitchNumber,lengthFt:p.length>0?Math.round(p.length*3.28084):null,grade:Object.values(p.grades||{}).filter(Boolean).join(' / '),description:standard(p.description)})),comments:[],photos:[],photoReferences:[],excludedNotes:0};
 const [notesResult,mediaResult]=await Promise.allSettled([gql('query Notes($id:ID){climb(uuid:$id){ticks{_id notes dateClimbed source}}}',{id}),media(id)]);
 if(notesResult.status==='fulfilled'){const all=notesResult.value.climb?.ticks||[];r.excludedNotes=all.filter(n=>n.notes&&n.source!=='OB').length;r.comments=all.filter(n=>n.source==='OB'&&n.notes?.trim()).map(n=>({id:n._id,text:standard(n.notes),date:n.dateClimbed||''})).sort((a,b)=>(a.date||'').localeCompare(b.date||''));}else{try{const fallback=await gql('query NotesWithoutDates($id:ID){climb(uuid:$id){ticks{_id notes source}}}',{id});const all=fallback.climb?.ticks||[];r.excludedNotes=all.filter(n=>n.notes&&n.source!=='OB').length;r.comments=all.filter(n=>n.source==='OB'&&n.notes?.trim()).map(n=>({id:n._id,text:standard(n.notes),date:''}));r.noteDatesUnavailable=true;}catch(_){r.commentsUnavailable=true;}}
 if(mediaResult.status==='fulfilled')r.photoReferences=mediaResult.value;else r.photoReferenceError='Photo references unavailable.';
 r.soWhat=brief(r);return r;
}
async function media(id){const result=[],seen=new Set();let after=null;do{const d=await gql('query Media($id:ID,$after:ID){climb(uuid:$id){mediaPagination(input:{first:50,after:$after}){mediaConnection{edges{cursor node{id mediaUrl username width height}}pageInfo{hasNextPage totalItems}}}}}',{id,after});const conn=d.climb?.mediaPagination?.mediaConnection;if(!conn)break;for(const edge of conn.edges||[]){const p=edge.node;if(p&&!seen.has(p.id)){seen.add(p.id);result.push({...p,license:'Reuse permission not provided by source; link only.'});}}if(!conn.pageInfo?.hasNextPage)break;const cursor=conn.edges?.at(-1)?.cursor;if(!cursor||cursor===after)throw Error('Incomplete photo pagination.');after=cursor;}while(true);return result;}
module.exports=async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'Use GET.'});const id=String(req.query.id||'');if(!uuid.test(id))return res.status(400).json({error:'Select an OpenBeta route result.'});try{const r=await getRoute(id);res.setHeader('Cache-Control','public, max-age=60, s-maxage=900');res.status(200).json(r);}catch(e){console.error(e.message);res.status(502).json({error:'Route information could not be retrieved ('+(e.name==='TimeoutError'?'source timeout':e.message)+'). Try again or enter the route manually.'});}};
module.exports.getRoute=getRoute;module.exports.gql=gql;
