// Source-based screening, not a claim about current conditions or an automated risk rating.
function plain(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\r/g,'').trim();}
function standard(s){return plain(s).replace(/(\d+(?:\.\d+)?)\s*(?:meters|metres|m)\b/g,(_,n)=>Math.round(+n*3.28084)+' ft').replace(/(\d+(?:\.\d+)?)\s*(?:kilometers|kilometres|km)\b/g,(_,n)=>(+n*0.621371).toFixed(1)+' mi');}
function brief(r){const notes=r.comments||[],entries=[['Climb description',r.description],['Approach / location',r.approach],['Protection',r.protection],...r.pitches.map(p=>['Pitch '+p.pitchNumber,p.description]),...notes.map((n,i)=>['Climber note '+(i+1)+' · climbed '+(n.date||'date unknown'),n.text])].filter(e=>e[1]);
 const sentences=entries.flatMap(([source,text])=>text.split(/(?<=[.!?])\s+|\n+/).filter(s=>s.trim()).map(text=>({source,text:text.trim()})));
 const rules=[
  ['Protection / fall consequence',/run[ -]?out|\bPG[ -]?13\b|\bR rated\b|\bX rated\b|poor pro|unprotected|no protection|ground[ -]?fall|ledge fall|bad bolts|rusty|loose bolts/i,'Verify protection spacing and fall consequences against the leader’s ability; set a bail decision before committing to the cited section.'],
  ['Anchors / retreat',/anchor|rappel|\brap\b|walk[ -]?off|descent|rope length|double ropes|two ropes/i,'Confirm the exact descent, anchor condition and rope requirements; budget time to reach the retreat option before your turnaround.'],
  ['Rock / ice condition',/loose rock|rockfall|choss|unstable|falling ice|thin ice|hollow ice|verglas|wet|seep|snow|avalanche/i,'Check today’s conditions at the cited terrain; adjust spacing, timing and retreat criteria for the reported hazard.'],
  ['Approach / navigation',/approach|bushwhack|route[ -]?finding|scrambl|exposed|wrong|off[ -]?route|gully|crossing/i,'Verify the approach and key route landmarks on the map; add time for the cited navigation or terrain issue and identify a regroup point.'],
  ['Rack / movement',/cam|nut|rack|off[ -]?width|chimney|wide crack|small gear|micro|bolt|screw/i,'Match the rack and movement capability to the cited features; confirm critical gear sizes and quantities before departure.'],
  ['Commitment / pace',/pitch|sustained|long day|slow|crowd|queue|biv|crux|harder|sandbag/i,'Use the cited pitch, crux or delay information when setting the team’s pace, transition allowance and turnaround time.']
 ];
 const findings=[];for(const [topic,pattern,impact] of rules){const hits=sentences.filter(s=>pattern.test(s.text));if(!hits.length)continue;const notesHits=hits.filter(s=>s.source.startsWith('Climber note'));const sourceHit=hits.find(s=>!s.source.startsWith('Climber note'));const examples=notesHits.length?[...(sourceHit?[sourceHit]:notesHits.slice(-2,-1)),notesHits.at(-1)]:hits.slice(0,2);const sample=examples.map(s=>'“'+(s.text.length>240?s.text.slice(0,237)+'…':s.text)+'” ['+s.source+']').join(' ');findings.push(topic+' ('+hits.length+' source mentions; '+notesHits.length+' climber notes): '+sample+' SO WHAT: '+impact);}
 const gaps=[];if(!r.grade)gaps.push('grade');if(!r.protection)gaps.push('protection');if(!r.approach)gaps.push('approach');if(!r.description)gaps.push('climb description');if(!r.pitches.length)gaps.push('structured pitch breakdown (absence does not establish a single-pitch climb)');
 const rating=r.safety&&r.safety!=='UNSPECIFIED'?' Reported protection rating: '+r.safety+'. Verify its route-specific implications before committing.':'';
 const dates=notes.map(n=>n.date).filter(Boolean).sort();
 return 'BLUF — '+r.name+': '+(r.grade?'reported grade '+r.grade:'grade unavailable')+'. Confirm leader/team capability, protection and retreat before committing.'+rating+'\n\n'+findings.join('\n\n')+'\n\nSOURCE REVIEW: All '+notes.length+' available native OpenBeta climber notes screened'+(dates.length?' (climbed dates '+dates[0]+' to '+dates[dates.length-1]+')':'')+'. '+(r.commentsUnavailable?'Climber notes could not be retrieved; comment review is incomplete. ':notes.length?'Notes are individual reports; conflicting statements are retained below for review. ':'No native OpenBeta notes returned; this is a route-text brief only. ')+(r.excludedNotes?'Imported third-party notes excluded: '+r.excludedNotes+'. ':'')+'Mountain Project comments are not accessed. Rule-based source screening can miss nuance; read the full source and notes below.\n'+(gaps.length?'INCOMPLETE: '+gaps.join('; ')+'.\n':'')+'These are historical route facts/reports, not verified current conditions or a completed risk assessment.\nSource: '+r.url+'\nRetrieved: '+r.retrieved;
}
module.exports={plain,standard,brief};
